name: Deploy ECS Task

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Authenticate with AWS and configure AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 318709527952.dkr.ecr.us-east-1.amazonaws.com  # Use your repository URL here

      # Build and push the Docker images
      - name: Build and push Docker images
        run: |
          docker build -t 318709527952.dkr.ecr.us-east-1.amazonaws.com/nginx-apache:latest .
          docker push 318709527952.dkr.ecr.us-east-1.amazonaws.com/nginx-apache:latest
      
      - name: Get latest task definition revision
        id: get-latest-revision
        run: |
          latest_revision=$(aws ecs describe-task-definition --task-definition arn:aws:ecs:us-east-1:318709527952:task-definition/nginx-apache | jq -r '.taskDefinition.revision')
          echo "::set-output name=latest-revision::$latest_revision"
      # Run the ECS task
      - name: Run ECS task
        run: aws ecs run-task --cluster newwcluster --task-definition nginx-apache

