name: Deploy ECS Task

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Authenticate with AWS and configure AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 318709527952.dkr.ecr.us-east-1.amazonaws.com  # Use your repository URL here

      # Build and push the Docker images
      - name: Build and push Docker images
        run: |
          docker build -t apache-image:latest .
          docker build -t nginx-image:latest .
          docker tag apache-image:latest 318709527952.dkr.ecr.us-east-1.amazonaws.com/apache-image:latest
          docker tag nginx-image:latest 318709527952.dkr.ecr.us-east-1.amazonaws.com/nginx-image:latest
          docker push 318709527952.dkr.ecr.us-east-1.amazonaws.com/apache-image:latest
          docker push 318709527952.dkr.ecr.us-east-1.amazonaws.com/nginx-image:latest
      
      # Register the ECS task definition
      - name: Register ECS task definition
        run: aws ecs register-task-definition --cli-input-json file://path/to/task-definition.json

      # Run the ECS task
      - name: Run ECS task
        run: aws ecs run-task --cluster newwcluster --task-definition nginx-apache

